---
- name: install Redis packages
  action: apt pkg="{{ item }}" state=present
  with_items:
    - redis-server
    - redis-tools

- name: Ensure latest redis confg is in place
  template: src=redis.conf.j2 dest=/etc/redis/redis.conf
  notify: restart redis
